# Generated by Django 5.0.2 on 2024-04-09 15:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Visual", "0002_alter_visualnote_note_label"),
    ]

    operations = [
        migrations.AlterField(
            model_name="visualnote",
            name="note_label",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="Visual.visuallabel",
            ),
        ),
    ]
