# Generated by Django 5.0.2 on 2024-04-12 20:17

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Visual", "0003_alter_visualnote_note_label"),
    ]

    operations = [
        migrations.AddField(
            model_name="visualnote",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
    ]
