# Generated by Django 5.0.2 on 2024-04-12 21:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Visual", "0004_visualnote_created_at"),
    ]

    operations = [
        migrations.CreateModel(
            name="SoundLabel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("label_name", models.CharField(max_length=15)),
            ],
        ),
        migrations.AlterField(
            model_name="visualnote",
            name="note_image",
            field=models.ImageField(blank=True, default=None, upload_to="images/"),
        ),
        migrations.CreateModel(
            name="SoundNote",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("note_title", models.CharField(max_length=30)),
                ("note_description", models.CharField(max_length=1200)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "note_label",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Visual.visuallabel",
                    ),
                ),
            ],
        ),
    ]
