# Generated by Django 5.0.2 on 2024-04-12 21:20

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("Visual", "0005_soundlabel_alter_visualnote_note_image_soundnote"),
    ]

    operations = [
        migrations.DeleteModel(
            name="SoundLabel",
        ),
        migrations.DeleteModel(
            name="SoundNote",
        ),
    ]
