# Generated by Django 5.0.2 on 2024-04-25 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Visual', '0006_delete_soundlabel_delete_soundnote'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visualnote',
            name='note_image',
            field=models.ImageField(blank=True, default=None, upload_to='Visual/static/images'),
        ),
    ]
