# Generated by Django 5.0.2 on 2024-04-25 15:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Visual", "0006_delete_soundlabel_delete_soundnote"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="visualnote",
            name="note_author",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="visualnote",
            name="note_image",
            field=models.ImageField(
                blank=True, default=None, upload_to="Visual/static/images"
            ),
        ),
    ]
