# Generated by Django 5.0.2 on 2024-05-02 02:10

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("Visual", "0007_alter_visualnote_note_image"),
        ("Visual", "0007_visualnote_note_author_alter_visualnote_note_image"),
    ]

    operations = []
