# Generated by Django 5.0.2 on 2024-04-09 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Forum', '0002_comment_testtext_alter_comment_thread'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='last_edited',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
