# Generated by Django 5.0.2 on 2024-04-25 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Forum', '0007_thread_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='thread',
            name='latest_comment_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='thread',
            name='latest_comment_username',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
