# Generated by Django 5.0.2 on 2024-04-21 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IdeaBoards', '0002_alter_ideaboard_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ideaboarditem',
            name='description',
            field=models.TextField(max_length=512),
        ),
        migrations.AlterField(
            model_name='ideaboarditem',
            name='title',
            field=models.CharField(max_length=64),
        ),
    ]
