# Generated by Django 5.0.2 on 2024-04-24 17:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("IdeaBoards", "0003_alter_ideaboarditem_description_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ideaboard",
            name="description",
            field=models.TextField(blank=True, default="", max_length=128),
        ),
        migrations.AlterField(
            model_name="ideaboard",
            name="title",
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name="ideaboarditem",
            name="description",
            field=models.TextField(),
        ),
    ]
