# Generated by Django 5.0.2 on 2024-04-28 23:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("IdeaBoards", "0005_ideaboarditem_board_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ideaboarditem",
            name="board_image",
            field=models.ImageField(
                blank=True,
                height_field="500",
                upload_to="board_image",
                width_field="500",
            ),
        ),
    ]
