# Generated by Django 5.0.2 on 2024-05-06 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IdeaBoards', '0010_alter_ideaboarditem_description_itemlabel_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ideaboard',
            name='is_public',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='ideaboarditem',
            name='label',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='ideaboarditem',
            name='board_image',
            field=models.ImageField(blank=True, null=True, upload_to='board_image/'),
        ),
        migrations.AlterField(
            model_name='ideaboarditem',
            name='board_sound',
            field=models.FileField(blank=True, null=True, upload_to='board_sounds/'),
        ),
    ]
