# Generated by Django 5.0.2 on 2024-05-07 00:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('IdeaBoards', '0011_ideaboard_is_public_ideaboarditem_label'),
        ('IdeaBoards', '0011_ideaboard_is_public_ideaboarditem_label_and_more'),
    ]

    operations = [
    ]
